version: 2
project_name: fauxrpc
builds:
  - main: ./cmd/fauxrpc/
    id: fauxrpc
    env:
    - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers_v2:
  - images:
      - "docker.io/sudorandom/fauxrpc"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "latest"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
    ids:
      - fauxrpc
checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: 'checksums.txt'
source:
  # https://goreleaser.com/customization/source/
  enabled: true
