# d2 assets/diagram.d2 --sketch --theme 201 assets/diagram.svg

Buf Schema Registry.shape: cloud
Buf Schema Registry -> Descriptors: buf build

Descriptors.label: Descriptors\nbinpb, json, txtpb, yaml
Descriptors.shape: document
Descriptors -> FauxRPC
Protobuf.shape: document
Protobuf -> FauxRPC
Protobuf -> Descriptors: buf build

FauxRPC.shape: oval
FauxRPC -> Microservices: gRPC {
  style: {
    bold: true
  }
}
FauxRPC -> Web Frontend: gRPC-Web {
  style: {
    bold: true
  }
}
FauxRPC -> Other Frontend: Connect {
  style: {
    bold: true
  }
}
FauxRPC -> REST API Client: REST {
  style: {
    bold: true
  }
}
